apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: trace-test-b
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/container-dependencies: "{app:[collector]}"
    spec:
      containers:
      - image: asia-northeast1-docker.pkg.dev/nova-we/run-otel/sample-metrics-app
        name: app
        ports:
        - containerPort: 8080
        env:
        - name: "OTEL_EXPORTER_OTLP_ENDPOINT"
          value: "http://localhost:4317"
      - image: asia-northeast1-docker.pkg.dev/nova-we/run-otel/otel-collector-metrics
        name: collector
        startupProbe:
          httpGet:
            path: /
            port: 13133
